# Generated by Django 6.0.2 on 2026-02-16 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WaterBottle',
            fields=[
                ('sku', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.CharField(max_length=50)),
                ('mouth_size', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('current_quantity', models.IntegerField()),
                ('supplied_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyInventoryApp.supplier')),
            ],
        ),
    ]
